# Generated by Django 4.2.11 on 2024-03-11 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Porfile',
            new_name='Profile',
        ),
    ]
