# Generated by Django 4.2.11 on 2024-03-11 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0002_rename_porfile_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=9888999728, max_length=15),
            preserve_default=False,
        ),
    ]
