# Generated by Django 4.2.11 on 2024-03-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0004_alter_skills_skill_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_experience',
            name='description',
            field=models.TextField(),
        ),
    ]
