# Generated by Django 4.2.11 on 2024-03-11 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio_App', '0005_alter_work_experience_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_experience',
            name='company_name',
            field=models.CharField(default=243234234, max_length=100),
            preserve_default=False,
        ),
    ]
